# Generated by Django 4.1.1 on 2022-10-14 20:52

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('text', ckeditor.fields.RichTextField(max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_twitter.profile')),
            ],
        ),
    ]
