# Generated by Django 4.1.1 on 2022-10-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_twitter', '0002_twitts'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitts',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='dislikes', to='main_twitter.profile'),
        ),
        migrations.AddField(
            model_name='twitts',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to='main_twitter.profile'),
        ),
    ]
